![Pandas logo](img/pandas.svg)

# Containers

Let us backup a little to understand what Pandas containers really are.  We have primarily given examples of DataFrames in earlier modules, and indeed that is the primary object you will work with.  Moreover, we loosely implied a Pandas DataFrame was a wrapper around a 2-D NumPy array; that is not a bad starting metaphor, but it is slightly wrong.

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from src.training import *

## Series

The basic data container in Pandas is actually a *Series*, not a DataFrame.  A `pd.Series` indeed wraps a NumPy array, but always a 1-D array.  The principle addition a Pandas Series gives us is labels on its rows.

In [2]:
arr1 = np.arange(10, 15)
arr2 = np.arange(1., 6)
arr3 = np.array(['foo', 'bar', 'baz', 'bam', 'fiz'])
s1, s2, s3 = (pd.Series(arr) for arr in (arr1, arr2, arr3))

In [3]:
print('arr1')
print(arr1)
print('s1')
print(s1)

arr1
[10 11 12 13 14]
s1
0    10
1    11
2    12
3    13
4    14
dtype: int64


For the most part, working with a Series or an array are similar with default indices (as we have used so far here). The screen display is a little bit different, but accessing items by index is the same. Indeed, most code that expects to work with 1-D NumPy arrays will seamlessly handle Pandas Series also.  You often do not need to think about the difference when writing functions.

In [4]:
# Slice
print('dtype:', arr1.dtype)
arr1[2:4]

dtype: int64


array([12, 13])

In [5]:
# Slice
s1[2:4]

2    12
3    13
dtype: int64

Where things are more evidently different is when the index is something different from successive integers starting at 0.

In [6]:
s_new = pd.Series(arr1, index=arr3)
s_new

foo    10
bar    11
baz    12
bam    13
fiz    14
dtype: int64

In [7]:
# Can access rows by meaningful names
s_new[['foo', 'bam']]

foo    10
bam    13
dtype: int64

In [8]:
# But can still use "accessor" to access by position
s_new.iloc[[0, 3]]

foo    10
bam    13
dtype: int64

In [9]:
# To avoid ambiguity, best practice uses accessor for index too
s_new.loc[['foo', 'bam']]

foo    10
bam    13
dtype: int64

## DataFrame

A DataFrame is **not** in fact a wrapper around a 2-D array, but more like a "bag" or "mapping" of column names to multiple Pandas Series.  An additional constraint (and capability) exists in DataFrames that all the Series contained in a DataFrame must use the same index.  This is a powerful abstraction.

One way to understand why DataFrames must be "bags" of 1-D structures is to think about the fact that they often contain different datatypes per column.  In contrast, N-dimensional arrays *always* have a homogeneous datatype across all values inside them.

In [10]:
df = pd.DataFrame({'Words': s3, 'Integers': s1, 'Floats': s2})
df

Words  Integers  Floats
0   foo        10     1.0
1   bar        11     2.0
2   baz        12     3.0
3   bam        13     4.0
4   fiz        14     5.0

We can absolutely work with these sequential integers as index.  But notice that the index is "sticky" in a way it is not for a 2-D NumPy array.

In [11]:
# After operations, index might not be sequential integers
df2 = df.loc[[0, 3]].copy()
df2

Words  Integers  Floats
0   foo        10     1.0
3   bam        13     4.0

In [12]:
# There is an index called '3'
df2.loc[3]

Words       bam
Integers     13
Floats      4.0
Name: 3, dtype: object

In [13]:
# But there is no index called '1'
try:
    print(df2.loc[1])
except Exception as err:
    print(err.__class__)

<class 'KeyError'>


In [14]:
arr2d = np.c_[arr1, arr2]
arr2d

array([[10.,  1.],
       [11.,  2.],
       [12.,  3.],
       [13.,  4.],
       [14.,  5.]])

In [15]:
arr2d_2 = arr2d[[0, 3]]
arr2d_2

array([[10.,  1.],
       [13.,  4.]])

In [16]:
# In contrast to DataFrame, array is always sequentially indexed
arr2d_2[1, :]

array([13.,  4.])

DataFrames may be created in numerous ways, both from input data files and with different patterns in the class initialization.  Many variants of these are left to the exercises.

## Index

Let us use one particular column as our index for an example.

In [17]:
df_names = df.set_index('Words')
df_names

Integers  Floats
Words                  
foo          10     1.0
bar          11     2.0
baz          12     3.0
bam          13     4.0
fiz          14     5.0

In [18]:
df_names.loc[['foo', 'bam']]

Integers  Floats
Words                  
foo          10     1.0
bam          13     4.0

We can use more general patterns to get at portions of the data by combining predicates (about rows) with column selectors.  As with NumPy, commas separate "dimensions." The index may be drawn from the `RangeIndex` that is applied by default, but the row labels will still remain after the selection.

In [20]:
cancer = pd.read_csv('data/wisconsin.csv')                     
focus = cancer.loc[cancer['mean radius'] > 24, ['mean radius','mean area']]
focus

mean radius  mean area
82         25.22     1878.0
122        24.25     1761.0
180        27.22     2250.0
212        28.11     2499.0
352        25.73     2010.0
461        27.42     2501.0
521        24.63     1841.0

In [21]:
cancer.index

RangeIndex(start=0, stop=569, step=1)

The ``RangeIndex`` is an efficient & lazy way to represent a sequence.

Other common **Index** types are

|    Class      |         Type of Values     |
|---------------|----------------------------|
|`Index`        | Anything, often strings    |
|`Int64Index`   | 64-bit integers            |
|`DatetimeIndex`| `TimeStamp` objects        |
|`RangeIndex`   | `range()`-like integers    |
|`MultiIndex`   | Hierarchical values        |

In [22]:
focus.index

Index([82, 122, 180, 212, 352, 461, 521], dtype='int64')

We might also choose an index by indicating it in the initializer, rather than by later calling `.set_index()` on the DataFrame.  Notice the crucial differences in this constructor:

* The columns are indicated with the keyword argument `data` and a dictionary
* The index is indicated with the keyword argument `index`
* We cannot use the Series that already have different row labels (index)
  * Can use original NumPy array for values
  * Can use series.array for unlabelled value
  * Can cast back to NumPy with `np.array(series)`

In [23]:
pd.DataFrame(data={'Integers': arr1, 'Floats': s2.array}, index=s3)

Integers  Floats
foo        10     1.0
bar        11     2.0
baz        12     3.0
bam        13     4.0
fiz        14     5.0

### Resetting index

We can always remove the index from a DataFrame, which will move the values back to a regular column.

In [24]:
df_names

Integers  Floats
Words                  
foo          10     1.0
bar          11     2.0
baz          12     3.0
bam          13     4.0
fiz          14     5.0

In [25]:
df_names.reset_index()

Words  Integers  Floats
0   foo        10     1.0
1   bar        11     2.0
2   baz        12     3.0
3   bam        13     4.0
4   fiz        14     5.0

In [26]:
df_names.loc[['foo', 'bam']].reset_index()

Words  Integers  Floats
0   foo        10     1.0
1   bam        13     4.0

In [27]:
# The column 'index' is probably pointless, but this follows from rule
df.reset_index()

index Words  Integers  Floats
0      0   foo        10     1.0
1      1   bar        11     2.0
2      2   baz        12     3.0
3      3   bam        13     4.0
4      4   fiz        14     5.0

# Exercises

The exercises below can each be done with a provided Python object.  These objects have a few properties.  Simply echoing the object in a cell produces a "pretty" display that may emphasize some aspect of the data of interest.

Each object has an `obj.data` attribute contains some sort of source data you should work with.  Each also contains an `obj.result` attribute that contains a some sort of transformation of the original data which you are trying to match.  In some cases, an exercise may have additional special attributes or methods that will be discussed in the description.

In [ ]:
from pprint import pprint
from src.pandas_exercises import *

Pandas DataFrames may be read from Python dictionaries of several different styles.  Try to replicate that transformation.  The *original* DataFrame is the familiar `patients` one. Some of these round-trips are lossy?  

Hint: you probably want to utilize the help system built into Jupyter to explore some details not shown in examples.  E.g. run `pd.DataFrame?` in a cell.

*Extra credit*: Think about how you might address the lossiness, where it is an issue.

In [ ]:
ex3_1.ideal

In [ ]:
# Row oriented
pprint(ex3_1.data)

In [ ]:
# Transform the dictionary
...

---

In [ ]:
# Record oriented
pprint(ex3_2.data)

In [ ]:
# Transform the dictionary
...

---

In [ ]:
# Column oriented
pprint(ex3_3)

In [ ]:
# Transform the dictionary
...

---

Using the same `patients` DateFrame we have used for a number of examples, set its index to an upper case version of the patient name, but retain the mixed case version as an additional column.  Since many names in various languages use varying capitalization rules, the transformation to upper case is a lossy operation and we do not want to discard information.

*Note:* While you are free to discover a more Pandas-native way of solving this, the standard Python `str.upper()` method is enough to arrive at an answer.  However, do not solve the problem purely manually (e.g. by simply typing the four names in upper case; pretend the DataFrame had thousands of records rather than just four).

In [ ]:
ex3_4

In [ ]:
# Transform data into result
...

---

Create a DataFrame based on a 2-D NumPy array (here of random values).  We want to name the rows with labels 'Alice', 'Bob', 'Carlos', 'Dan', and the columns with labels 'key1', 'key2', 'key3', 'key4'.  These choices are reminiscent of names often used in cryptography, but these specific values have no special connection to that.

In [ ]:
ex3_5

In [ ]:
# Create a DataFrame based on data and matching result
...

Having solved the problem one way, see if you can play around with Pandas methods for constructing DataFrames to create an equal DataFrame using different APIs.

In [ ]:
# Create DataFrame from data, matching result (2nd approach)
...

---
Based on a Series containing platform-native integer values, construct a DataFrame with columns named 'Int16', 'Float32', 'Complex', and 'String'.  The values inside each column should be "the same" as those in the Series, but their types should correspond to the column names.

*Extra credit:* Also set the index of the DataFrame you build be the value in their original datatype.

In [ ]:
ex3_6

In [ ]:
print(ex3_6.result.dtypes)
print(ex3_6.result.index)

In [ ]:
# Create a DataFrame based on Series data, with columns described
...